### ISSUE TITLE
Custom slugs

### ISSUE THREAD

**Issue by pawandubey** [pawandubey/griffin#16]
Users should be able to specify custom slugs for their posts and pages, which will be an optional header parameter called "slug". If no slug is specified, or is an empty string, then fallback onto the title for slug generation. The Parsable interface should require a slug field. Modify the code accordingly.

see Parser.writeFile method for output file naming.
Additional: refactor to delegate the slug generation to the appropriate class instead of the Parser class. Better OOP.

**Comment by pawandubey** [comment]
@shubhekshajalan fancy this?

**Comment by pawandubey** [comment]
Done.

**Comment by shubheksha** [comment]
The space issue is fixed?

**Comment by pawandubey** [comment]
No. Didnt check. Or try to reproduce.

**Comment by shubheksha** [comment]
Then why did you close it?

**Comment by pawandubey** [comment]
Fixed here: b2dba63feec310b49c57629f35a71d61a9f6415e
